### ISSUE TITLE
Activity M

### ISSUE THREAD

**Issue by msayan** [mustafakuloglu/ecommerce#12]

**Comment by CBaldemir** [comment]
Tamamlandı.  @msayan @dtunctuncer

**Comment by msayan** [comment]
ortalı değil, paddingler düzenlensin, divider incelsin

**Comment by CBaldemir** [comment]
@msayan @dtunctuncer  Düzenlemeler yapıldı.

**Comment by dtunctuncer** [comment]
ekran emulatorde patlıyor

**Comment by CBaldemir** [comment]
@msayan @dtunctuncer Düzenlendi
