### ISSUE TITLE
Activity I

### ISSUE THREAD

**Issue by msayan** [mustafakuloglu/ecommerce#8]

**Comment by CBaldemir** [comment]
Tamamlandı. @msayan @dtunctuncer

**Comment by msayan** [comment]
padding düzenlensin,yazılar düzenlensin(bold),çizgi incelsin

**Comment by CBaldemir** [comment]
@msayan @dtunctuncer Düzenlemeler yapıldı.

**Comment by dtunctuncer** [comment]
olmamış bence 2sini emulatorde yan yana koyarak bir kontrol etmen lazım direk o görüntünün aynısını istiyoruz

**Comment by CBaldemir** [comment]
Düzenlendi @msayan @dtunctuncer
