### ISSUE TITLE
Activity J

### ISSUE THREAD

**Issue by msayan** [mustafakuloglu/ecommerce#9]

**Comment by mustafakuloglu** [comment]
52c382babafc7ed55cf6cb6b03e29f75cb0edd8c tamamlandı. @msayan @dtunctuncer

**Comment by dtunctuncer** [comment]
bu pek olmamış gibi tekrar bakabilir misin ? @mustafakuloglu

**Comment by mustafakuloglu** [comment]
ee3a5341daabdcdad04b05ab014c35f5eb0bf395 yukarıdaki link yanlış yere gidior. eğer onla ilgili bir sıkıntı yoksa nerede yanlışlık olduğunu söyleyebilir misin.

**Comment by msayan** [comment]
radiobutton oraya boşluk konacak
